### ISSUE TITLE
截取的部分也有蒙版图层的灰色

### ISSUE THREAD

**Issue by bettersun** [YangShuangjie/orchid#2]
感觉截取的部分也有蒙版图层的灰色，截出来的图片是灰蒙蒙的。

**Comment by young2j** [comment]
这个不是蒙版的灰色。我猜你的电脑肯定是高清屏，canvas渲染会模糊(你可以浏览器打开控制台看看window.devicePixelRatio是否大于1)。我找了很多资料，百度、博客，按照已有的方案依然没有很好的解决这个问题。但我在另一台电脑linux下几乎不存在这个问题。
还有一个可能的原因，知乎上有篇文章说electron的desktopCapture捕获的桌面颜色值会有差异。

**Comment by bettersun** [comment]
非常感谢及时回复。
第一次启动貌似没有问题，点上几次后就会重现。
用的是Windows10。
